set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

fish_config theme choose "Catppuccin Mocha"

atuin gen-completions --shell fish | source


status is-login; and begin

    # Login shell initialisation


end

status is-interactive; and begin

    # Abbreviations
    abbr --add -- cf 'xclip -sel clip '
    abbr --add -- e. 'nautilus .'
    abbr --add -- ga 'git add -A'
    abbr --add -- gc 'git commit'
    abbr --add -- gdn 'git diff --name-only'
    abbr --add -- gp 'git pull'
    abbr --add -- gps 'git push'
    abbr --add -- gs 'git status'
    abbr --add -- ld lazydocker
    abbr --add -- lg lazygit
    abbr --add -- n. 'nvim .'
    abbr --add -- nd. 'develop -c "nvim ."'
    abbr --add -- oo 'cd $HOME/Documents/BIG && nvim .'
    abbr --add -- dpup 'devpod up . --provider docker --recreate --dotfiles https://github.com/ferrumboll/dotfiles'
    abbr --add -- gdr "git branch -vv | awk '/: gone]/{print \$1}' | xargs -r git branch -D"

    # Aliases
    alias la 'eza -a'
    alias ll 'eza -l'
    alias lla 'eza -la'
    alias ls eza
    alias lt 'eza --tree'
    alias n nvim
    alias stl streamlink
    alias vim nvim

    # Interactive shell initialisation
    fzf --fish | source
    starship init fish | source

    zoxide init fish | source

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/fer/.local/share/fish/home-manager_generated_completions" $post
    end

    atuin init fish | source

    set BAT_THEME "Catppuccin Mocha"

    switch (uname)
        case Darwin
            set -x PATH /opt/homebrew/bin $PATH
            set -x PATH /opt/homebrew/sbin $PATH
            set -x PATH /opt/homebrew/opt/node@22/bin $PATH
            set -x PATH /Applications/SnowSQL.app/Contents/MacOS $PATH
    end
end
fish_add_path /Users/fernando.llanos/.local/bin

# dbt aliases
alias dbtf=/Users/fernando.llanos/.local/bin/dbt

# opencode
fish_add_path /Users/fernando.llanos/.opencode/bin
